### ISSUE TITLE
Unable to build GSI

### ISSUE THREAD

**Issue by sandhoners123** [erfanoabdi/ErfanGSIs#113]
Traceback (most recent call last):
  File "/home/tmp/ErfanGSIs/tools/update_payload_extractor/extract.py", line 7, in <module>
    import update_payload
  File "/home/bristlefrost/ErfanGSIs/tools/update_payload_extractor/update_payload/__init__.py", line 20, in <module>
    from update_payload.checker import CHECKS_TO_DISABLE
  File "/home/bristlefrost/ErfanGSIs/tools/update_payload_extractor/update_payload/checker.py", line 36, in <module>
    from update_payload import common
  File "/home/bristlefrost/ErfanGSIs/tools/update_payload_extractor/update_payload/common.py", line 28
    PSEUDO_EXTENT_MARKER = (1L << 64) - 1  # UINT64_MAX

This is for latest oneplus 7t pro firmware and oxygenos

**Comment by koumaza** [comment]
Please use Python2.
This happens in Python3.
