### ISSUE TITLE
toos: Resigning to AOSP keys  Stop

### ISSUE THREAD

**Issue by xiang473535976** [erfanoabdi/ErfanGSIs#70]
root@ubuntu:/home/ac# cd ErfanGSIs
root@ubuntu:/home/ac/ErfanGSIs# ./url2GSI.sh http://romdownload.nubia.com/nubiaX/V3.11/NX616J-update.zip  Nubia
Updating tools...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
展开对象中: 100% (4/4), 完成.
来自 https://github.com/erfanoabdi/ErfanGSIs
   7489d5e..39068be  master     -> origin/master
Fetching submodule prebuilt/vendor_vndk
Fetching submodule tools/ROM_resigner
Fetching submodule tools/oppo_ozip_decrypt
来自 https://github.com/bkerler/oppo_ozip_decrypt
   f27894b..f454f60  master     -> origin/master
Fetching submodule tools/update_payload_extractor
更新 7489d5e..39068be
Fast-forward
 scripts/mkimage.sh | 1 +
 1 file changed, 1 insertion(+)
Downloading firmware to: /home/ac/ErfanGSIs/input/4771_FIRMWARE.tgz
--2019-09-21 15:07:11--  http://romdownload.nubia.com/nubiaX/V3.11/NX616J-update.zip
正在解析主机 romdownload.nubia.com (romdownload.nubia.com)... 182.140.139.105, 118.123.0.236, 118.123.208.229
正在连接 romdownload.nubia.com (romdownload.nubia.com)|182.140.139.105|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度： 2802499919 (2.6G) [application/octet-stream]
正在保存至: “/home/ac/ErfanGSIs/input/4771_FIRMWARE.tgz”
Create Temp and out dir
Extracting firmware on: /home/ac/ErfanGSIs/working
Aonly OTA detected
Converting brotli system dat to normal
Extracting system
Create Temp dir
Making copy of source rom to temp
Resigning to AOSP keys

Patching started...
Start Patching Light Services for Brightness Fix...
Create Temp dir
Creating Image: Nubia-AB-9-20190921-ErfanGSI.img
Remove Temp dir
Create Temp dir
Making copy of source rom to temp
Resigning to AOSP keys

stop at  here__   can not  continue 
plz  see it  ,

**Comment by xiang473535976** [comment]
Break signaled
Traceback (most recent call last):
  File "/home/ac/ErfanGSIs/tools/ROM_resigner/resign.py", line 98, in <module>
    getcert(jarfile, out)
  File "/home/ac/ErfanGSIs/tools/ROM_resigner/resign.py", line 44, in getcert
    output = subprocess.check_output(['bash','-c', extractjar])
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '-c', '7z e /home/ac/ErfanGSIs/tmp/system/system/priv-app/SelfStartProvider/SelfStartProvider.apk META-INF/CERT.RSA -o/home/ac/ErfanGSIs/tools/ROM_resigner/tmp']' returned non-zero exit status 255
